### ISSUE TITLE
Labels not show correctly

### ISSUE THREAD

**Issue by FranklinMCA** [thiago1255/IndustrialWiresPlus#7]
[
![2023-12-12_11 43 23](https://github.com/thiago1255/IndustrialWiresPlus/assets/58149488/9cd1e6f3-e50d-4205-a227-60132ccd1674)
](url)

Idk which causes the bug.

**Comment by thiago1255** [comment]
What exactly is the bug ?
Can u send a screenshot of the components you are using to build the panel ?

**Comment by FranklinMCA** [comment]
Labels and meters, so everything which have text

**Comment by FranklinMCA** [comment]
I don't know if another mod is causing the problem

**Comment by thiago1255** [comment]
Oh i see now, they are missing !
Yes that can be the cause. Do you have graphic mods such optifine ?

**Comment by FranklinMCA** [comment]
I have Optifine, LoliASM, UniversalTweaks, Sledgehammer, BetterFPS, RandomPatches

**Comment by FranklinMCA** [comment]
oh and VintageFix of course

**Comment by FranklinMCA** [comment]
I did not get this error when using Foamfix, only with VintageFix. I'm sending you both config files to find out what causes this bug.

FoamFix version is 0.10.15 and VintageFix 0.3.3.

FoamFix configuration: https://mclo.gs/NNR1QDi
VintageFix configuration: https://mclo.gs/UbYjaDh
