### ISSUE TITLE
Industrial Wires Exploding Issue

### ISSUE THREAD

**Issue by bwiggin10** [thiago1255/IndustrialWiresPlus#8]
When trying to utilize any of the industrial wires to connect an Immersive Engineering capacitor to IC2 machines they just explode.

Is this just user error or some kind of bug? This mod is included in Enigmatica 2 Expert - Extended. Wasn't sure if it was a bug, something wrong with the config, mod conflict, user error or something else entirely.

Hoping to get pointed in the right direction to provie any needed information.

Version Info - On latest versions of IC2, Immersive Engineering and the latest of this mod.

**Comment by thiago1255** [comment]
Its because EU and IF should not be mixed, thats why the original mod add mechanical converters and this fork adds retifier valve.
